/**
 * Author:  pho
 * Created: 09.01.2016
 */
SET SCHEMA 'descent';

/** CAMPAIGNS
INSERT INTO PLAYER (ID, USERNAME, PASSWORD, DEACTIVE) VALUES (1, 'test', 'Hzi8HmbWqSgEQPT48Vsx3Bu9j0gCgM0MTgSVUNlbG9uaXMgUGFydG5lciBMaWNlbnNlIGZvciBFbm93YSAtIFNpbmdsZSBVc2VyIERlbW8gTGljZW5zZTogTm90I5xUYIZvpvEP7KggDqIJLvhxsoe6gWPnkVzfZtBFc+7BoBBaFyVXvj29EPr7XesP', false);
INSERT INTO PLAYER (ID, USERNAME, PASSWORD, DEACTIVE) VALUES (2, 'test1', '90f//wFb14DFP1TRdjR8FiFMqAkCgM0MTgSVUNlbG9uaXMgUGFydG5lciBMaWNlbnNlIGZvciBFbm93YSAtIFNpbmdsZSBVc2VyIERlbW8gTGljZW5zZTogTm90I5xUYIZvpvEP7KggDqIJLvhxsoe6gWPnkVzfZtBFc+7BoBBaFyVXvj29EPr7XesP', false);
INSERT INTO PLAYER (ID, USERNAME, PASSWORD, DEACTIVE) VALUES (3, 'test2', '/pr4No/Uuxgo1UVEcY+MdfDB1aICgM0MTgSVUNlbG9uaXMgUGFydG5lciBMaWNlbnNlIGZvciBFbm93YSAtIFNpbmdsZSBVc2VyIERlbW8gTGljZW5zZTogTm90I5xUYIZvpvEP7KggDqIJLvhxsoe6gWPnkVzfZtBFc+7BoBBaFyVXvj29EPr7XesP', false);
INSERT INTO PLAYER (ID, USERNAME, PASSWORD, DEACTIVE) VALUES (4, 'test3', 'ZNyumiLtEj5JalkoKcXBVhqiLm4CgM0MTgSVUNlbG9uaXMgUGFydG5lciBMaWNlbnNlIGZvciBFbm93YSAtIFNpbmdsZSBVc2VyIERlbW8gTGljZW5zZTogTm90I5xUYIZvpvEP7KggDqIJLvhxsoe6gWPnkVzfZtBFc+7BoBBaFyVXvj29EPr7XesP', false);
INSERT INTO PLAYER (ID, USERNAME, PASSWORD, DEACTIVE) VALUES (5, 'test4', '3liBjHe6CZAWTGl9Gg0r34bfGrcCgM0MTgSVUNlbG9uaXMgUGFydG5lciBMaWNlbnNlIGZvciBFbm93YSAtIFNpbmdsZSBVc2VyIERlbW8gTGljZW5zZTogTm90I5xUYIZvpvEP7KggDqIJLvhxsoe6gWPnkVzfZtBFc+7BoBBaFyVXvj29EPr7XesP', false);
 */

/** GAMEMAPS */
INSERT INTO GAMEMAP (ID, GRIDXSIZE, GRIDYSIZE, IMAGEPATH) VALUES (1,13,12,'/img/encounter/First_Blood.png');

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (1,6,1,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (2,7,1,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (3,8,1,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (4,9,1,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (5,2,2,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (6,3,2,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (7,5,2,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (8,6,2,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (9,7,2,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (10,8,2,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (11,9,2,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (12,2,3,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (13,3,3,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (14,5,3,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (15,6,3,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (16,7,3,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (17,8,3,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (18,9,3,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (19,2,4,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (20,3,4,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (21,6,4,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (22,7,4,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (23,8,4,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (24,9,4,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (25,1,5,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (26,2,5,2,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (27,3,5,2,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (28,7,5,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (29,8,5,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (30,11,5,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (31,12,5,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (32,1,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (33,2,6,2,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (34,3,6,2,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (35,4,6,2,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (36,5,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (37,6,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (38,7,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (39,8,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (40,9,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (41,10,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (42,11,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (43,12,6,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (44,13,6,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (45,1,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (46,2,7,2,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (47,3,7,2,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (48,4,7,2,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (49,5,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (50,6,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (51,7,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (52,8,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (53,9,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (54,10,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (55,11,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (56,12,7,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (57,13,7,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (58,1,8,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (59,2,8,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (60,3,8,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (61,4,8,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (62,7,8,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (63,8,8,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (64,11,8,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (65,12,8,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (66,6,9,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (67,7,9,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (68,8,9,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (69,9,9,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (70,5,10,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (71,6,10,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (72,7,10,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (73,8,10,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (74,9,10,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (75,10,10,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (76,11,10,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (77,5,11,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (78,6,11,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (79,7,11,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (80,8,11,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (81,9,11,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (82,10,11,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (83,11,11,1,true,1);

INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (84,6,12,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (85,7,12,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (86,8,12,1,true,1);
INSERT INTO MAPFIELD (ID,XPOS,YPOS,MOVECOST,ISPASSABLE,MAP_ID) VALUES (87,9,12,1,true,1);

/** QUESTENCOUNTERS */
INSERT INTO QUESTENCOUNTER (ID,QUEST,PART,ISACTIVE,ACTIVEHERO_ID,WINNER,MAP_ID) VALUES (1, 'FIRST_BLOOD', 'FIRST', true, null, null, 1);