package de.pho.descent.shared.model.monster;

/**
 *
 * @author pho
 */
public enum MonsterTemplate {

    ZOMBIE_NORMAL_ACT1,
    ZOMBIE_ELITE_ACT1,
    ZOMBIE_NORMAL_ACT2,
    ZOMBIE_ELITE_ACT2,
    GOBLIN_ARCHER_NORMAL_ACT1,
    GOBLIN_ARCHER_ELITE_ACT1,
    GOBLIN_ARCHER_NORMAL_ACT2,
    GOBLIN_ARCHER_ELITE_ACT2,
    CAVE_SPIDER_NORMAL_ACT1,
    CAVE_SPIDER_ELITE_ACT1,
    CAVE_SPIDER_NORMAL_ACT2,
    CAVE_SPIDER_ELITE_ACT2,
    FLESH_MOULDER_NORMAL_ACT1,
    FLESH_MOULDER_ELITE_ACT1,
    FLESH_MOULDER_NORMAL_ACT2,
    FLESH_MOULDER_ELITE_ACT2,
    BARGHEST_NORMAL_ACT1,
    BARGHEST_ELITE_ACT1,
    BARGHEST_NORMAL_ACT2,
    BARGHEST_ELITE_ACT2,
    ETTIN_NORMAL_ACT1,
    ETTIN_ELITE_ACT1,
    ETTIN_NORMAL_ACT2,
    ETTIN_ELITE_ACT2,
    ELEMENTAL_NORMAL_ACT1,
    ELEMENTAL_ELITE_ACT1,
    ELEMENTAL_NORMAL_ACT2,
    ELEMENTAL_ELITE_ACT2,
    MERRIOD_NORMAL_ACT1,
    MERRIOD_ELITE_ACT1,
    MERRIOD_NORMAL_ACT2,
    MERRIOD_ELITE_ACT2,
    SHADOW_DRAGON_NORMAL_ACT1,
    SHADOW_DRAGON_ELITE_ACT1,
    SHADOW_DRAGON_NORMAL_ACT2,
    SHADOW_DRAGON_ELITE_ACT2;
}
